export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const INDIAN_CITIES = [
  "Agra","Ahmedabad","Ahmednagar","Aizawl","Ajmer","Akola","Aligarh","Allahabad","Alwar","Ambala","Amravati","Amritsar","Anand","Anantapur","Asansol","Aurangabad",
  "Bahraich","Balasore","Ballari","Banda","Bangalore","Bareilly","Bathinda","Belgaum","Bellary","Bengaluru","Bhagalpur","Bharatpur","Bharuch","Bhavnagar","Bhilai","Bhilwara","Bhiwandi","Bhopal","Bhubaneswar","Bhuj","Bidar","Bijapur","Bikaner","Bilaspur","Bokaro","Brahmapur","Buxar",
  "Chandigarh","Chandrapur","Chennai","Chhapra","Chhatarpur","Chhindwara","Chhattarpur","Chikkamagaluru","Chitradurga","Chittoor","Coimbatore","Cuddalore","Cuttack",
  "Darbhanga","Darjeeling","Davanagere","Dehradun","Delhi","Deoghar","Dewas","Dhanbad","Dharwad","Dhule","Dibrugarh","Dimapur","Dindigul","Dispur","Durgapur",
  "Eluru","Erode",
  "Faizabad","Faridabad","Farrukhabad","Fatehpur","Firozabad","Firozpur",
  "Gandhinagar","Gangtok","Gaya","Ghaziabad","Giridih","Godhra","Gorakhpur","Greater Noida","Gulbarga","Guntur","Gurgaon","Gurugram","Guwahati","Gwalior",
  "Haldia","Haldwani","Hapur","Haridwar","Hassan","Hazaribagh","Hisar","Hosur","Howrah","Hubli","Hyderabad",
  "Imphal","Indore","Itanagar",
  "Jabalpur","Jagdalpur","Jaipur","Jaisalmer","Jalandhar","Jalgaon","Jalna","Jammu","Jamnagar","Jamshedpur","Jaunpur","Jhansi","Jhunjhunu","Jodhpur","Jorhat","Junagadh",
  "Kadapa","Kaithal","Kakinada","Kalyan","Kanchipuram","Kannur","Kanpur","Karimnagar","Karnal","Karur","Kavaratti","Khammam","Kharagpur","Kochi","Kohima","Kolar","Kolhapur","Kolkata","Kollam","Korba","Kota","Kottayam","Kozhikode","Krishnanagar","Kurnool",
  "Latur","Loni","Lucknow","Ludhiana",
  "Machilipatnam","Madurai","Malappuram","Malda","Mandi","Mandya","Mangalore","Mangaluru","Manipal","Mapusa","Margao","Mathura","Meerut","Mehsana","Mira-Bhayandar","Mirzapur","Moradabad","Morbi","Morena","Mumbai","Munger","Muzaffarnagar","Muzaffarpur","Mysore","Mysuru",
  "Nagaon","Nagercoil","Nagpur","Naihati","Nainital","Nanded","Nandyal","Nashik","Navi Mumbai","Nellore","New Delhi","Nizamabad","Noida",
  "Ongole",
  "Palakkad","Palghar","Pali","Panaji","Panchkula","Panipat","Panvel","Paradip","Pathankot","Patiala","Patna","Pilibhit","Pimpri-Chinchwad","Pondicherry","Porbandar","Port Blair","Prayagraj","Puducherry","Pune","Puri","Purnia",
  "Raebareli","Raichur","Raigarh","Raipur","Rajahmundry","Rajkot","Rajnandgaon","Ramagundam","Rampur","Ranchi","Ratlam","Ratnagiri","Rewa","Rewari","Rishikesh","Roorkee","Rourkela",
  "Sagar","Saharanpur","Salem","Sambalpur","Sangli","Sasaram","Satara","Satna","Secunderabad","Shahjahanpur","Shillong","Shimla","Shimoga","Shivamogga","Sikar","Silchar","Siliguri","Silvassa","Sirsa","Sitapur","Solapur","Sonipat","Srikakulam","Srinagar","Sultanpur","Surat","Surendranagar",
  "Tadepalligudem","Tenali","Thane","Thanjavur","Theni","Thiruvananthapuram","Thoothukudi","Thrissur","Tiruchirappalli","Tirunelveli","Tirupati","Tiruppur","Tiruvannamalai","Tumkur","Tuticorin",
  "Udaipur","Udupi","Ujjain","Ulhasnagar","Unnao",
  "Vadodara","Valsad","Vapi","Varanasi","Vasai-Virar","Vellore","Vijayawada","Visakhapatnam","Vizianagaram",
  "Warangal","Wardha",
  "Yamunanagar","Yavatmal",
];
