/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as PostpartumRouteImport } from './routes/postpartum'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KicksRouteImport } from './routes/kicks'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DietRouteImport } from './routes/diet'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekWeekRouteImport } from './routes/week.$week'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as BabyVaccinationsRouteImport } from './routes/baby.vaccinations'
import { Route as BabyGrowthRouteImport } from './routes/baby.growth'
import { Route as BabyFeedsRouteImport } from './routes/baby.feeds'
import { Route as BabyCareRouteImport } from './routes/baby.care'

const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const PostpartumRoute = PostpartumRouteImport.update({
  id: '/postpartum',
  path: '/postpartum',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KicksRoute = KicksRouteImport.update({
  id: '/kicks',
  path: '/kicks',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekRoute = WeekWeekRouteImport.update({
  id: '/week/$week',
  path: '/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const BabyVaccinationsRoute = BabyVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => BabyRoute,
} as any)
const BabyGrowthRoute = BabyGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => BabyRoute,
} as any)
const BabyFeedsRoute = BabyFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => BabyRoute,
} as any)
const BabyCareRoute = BabyCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => BabyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/diet': typeof DietRoute
  '/home': typeof HomeRoute
  '/kicks': typeof KicksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/tracker': typeof TrackerRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/diet': typeof DietRoute
  '/home': typeof HomeRoute
  '/kicks': typeof KicksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/tracker': typeof TrackerRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/diet': typeof DietRoute
  '/home': typeof HomeRoute
  '/kicks': typeof KicksRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/tracker': typeof TrackerRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/diet'
    | '/home'
    | '/kicks'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/postpartum'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/tracker'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/diet'
    | '/home'
    | '/kicks'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/postpartum'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/tracker'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/diet'
    | '/home'
    | '/kicks'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/postpartum'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/tracker'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BabyRoute: typeof BabyRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  DietRoute: typeof DietRoute
  HomeRoute: typeof HomeRoute
  KicksRoute: typeof KicksRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  OnboardingRoute: typeof OnboardingRoute
  PostpartumRoute: typeof PostpartumRoute
  SchemesRoute: typeof SchemesRoute
  SignupRoute: typeof SignupRoute
  SymptomsRoute: typeof SymptomsRoute
  TrackerRoute: typeof TrackerRoute
  YogaRoute: typeof YogaRoute
  WeekWeekRoute: typeof WeekWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postpartum': {
      id: '/postpartum'
      path: '/postpartum'
      fullPath: '/postpartum'
      preLoaderRoute: typeof PostpartumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kicks': {
      id: '/kicks'
      path: '/kicks'
      fullPath: '/kicks'
      preLoaderRoute: typeof KicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$week': {
      id: '/week/$week'
      path: '/week/$week'
      fullPath: '/week/$week'
      preLoaderRoute: typeof WeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/baby/vaccinations': {
      id: '/baby/vaccinations'
      path: '/vaccinations'
      fullPath: '/baby/vaccinations'
      preLoaderRoute: typeof BabyVaccinationsRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/growth': {
      id: '/baby/growth'
      path: '/growth'
      fullPath: '/baby/growth'
      preLoaderRoute: typeof BabyGrowthRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/feeds': {
      id: '/baby/feeds'
      path: '/feeds'
      fullPath: '/baby/feeds'
      preLoaderRoute: typeof BabyFeedsRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/care': {
      id: '/baby/care'
      path: '/care'
      fullPath: '/baby/care'
      preLoaderRoute: typeof BabyCareRouteImport
      parentRoute: typeof BabyRoute
    }
  }
}

interface BabyRouteChildren {
  BabyCareRoute: typeof BabyCareRoute
  BabyFeedsRoute: typeof BabyFeedsRoute
  BabyGrowthRoute: typeof BabyGrowthRoute
  BabyVaccinationsRoute: typeof BabyVaccinationsRoute
}

const BabyRouteChildren: BabyRouteChildren = {
  BabyCareRoute: BabyCareRoute,
  BabyFeedsRoute: BabyFeedsRoute,
  BabyGrowthRoute: BabyGrowthRoute,
  BabyVaccinationsRoute: BabyVaccinationsRoute,
}

const BabyRouteWithChildren = BabyRoute._addFileChildren(BabyRouteChildren)

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BabyRoute: BabyRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  DietRoute: DietRoute,
  HomeRoute: HomeRoute,
  KicksRoute: KicksRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  OnboardingRoute: OnboardingRoute,
  PostpartumRoute: PostpartumRoute,
  SchemesRoute: SchemesRoute,
  SignupRoute: SignupRoute,
  SymptomsRoute: SymptomsRoute,
  TrackerRoute: TrackerRoute,
  YogaRoute: YogaRoute,
  WeekWeekRoute: WeekWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
