/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VaccinesPregnancyRouteImport } from './routes/vaccines-pregnancy'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PostpartumRouteImport } from './routes/postpartum'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionGuideRouteImport } from './routes/nutrition-guide'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MedsSafetyRouteImport } from './routes/meds-safety'
import { Route as MedicalDisclaimerRouteImport } from './routes/medical-disclaimer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaborSignsRouteImport } from './routes/labor-signs'
import { Route as KicksRouteImport } from './routes/kicks'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DietRouteImport } from './routes/diet'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekWeekRouteImport } from './routes/week.$week'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as BabyVaccinationsRouteImport } from './routes/baby.vaccinations'
import { Route as BabyGrowthRouteImport } from './routes/baby.growth'
import { Route as BabyFeedsRouteImport } from './routes/baby.feeds'
import { Route as BabyCareRouteImport } from './routes/baby.care'

const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinesPregnancyRoute = VaccinesPregnancyRouteImport.update({
  id: '/vaccines-pregnancy',
  path: '/vaccines-pregnancy',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostpartumRoute = PostpartumRouteImport.update({
  id: '/postpartum',
  path: '/postpartum',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionGuideRoute = NutritionGuideRouteImport.update({
  id: '/nutrition-guide',
  path: '/nutrition-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MedsSafetyRoute = MedsSafetyRouteImport.update({
  id: '/meds-safety',
  path: '/meds-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalDisclaimerRoute = MedicalDisclaimerRouteImport.update({
  id: '/medical-disclaimer',
  path: '/medical-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborSignsRoute = LaborSignsRouteImport.update({
  id: '/labor-signs',
  path: '/labor-signs',
  getParentRoute: () => rootRouteImport,
} as any)
const KicksRoute = KicksRouteImport.update({
  id: '/kicks',
  path: '/kicks',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekRoute = WeekWeekRouteImport.update({
  id: '/week/$week',
  path: '/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const BabyVaccinationsRoute = BabyVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => BabyRoute,
} as any)
const BabyGrowthRoute = BabyGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => BabyRoute,
} as any)
const BabyFeedsRoute = BabyFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => BabyRoute,
} as any)
const BabyCareRoute = BabyCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => BabyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/consent': typeof ConsentRoute
  '/diet': typeof DietRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/investigations': typeof InvestigationsRoute
  '/kicks': typeof KicksRoute
  '/labor-signs': typeof LaborSignsRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/meds-safety': typeof MedsSafetyRoute
  '/more': typeof MoreRoute
  '/nutrition-guide': typeof NutritionGuideRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/vaccines-pregnancy': typeof VaccinesPregnancyRoute
  '/welcome': typeof WelcomeRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/consent': typeof ConsentRoute
  '/diet': typeof DietRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/investigations': typeof InvestigationsRoute
  '/kicks': typeof KicksRoute
  '/labor-signs': typeof LaborSignsRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/meds-safety': typeof MedsSafetyRoute
  '/more': typeof MoreRoute
  '/nutrition-guide': typeof NutritionGuideRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/vaccines-pregnancy': typeof VaccinesPregnancyRoute
  '/welcome': typeof WelcomeRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/baby': typeof BabyRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/consent': typeof ConsentRoute
  '/diet': typeof DietRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/investigations': typeof InvestigationsRoute
  '/kicks': typeof KicksRoute
  '/labor-signs': typeof LaborSignsRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/meds-safety': typeof MedsSafetyRoute
  '/more': typeof MoreRoute
  '/nutrition-guide': typeof NutritionGuideRoute
  '/onboarding': typeof OnboardingRoute
  '/postpartum': typeof PostpartumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/vaccines-pregnancy': typeof VaccinesPregnancyRoute
  '/welcome': typeof WelcomeRoute
  '/yoga': typeof YogaRoute
  '/baby/care': typeof BabyCareRoute
  '/baby/feeds': typeof BabyFeedsRoute
  '/baby/growth': typeof BabyGrowthRoute
  '/baby/vaccinations': typeof BabyVaccinationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/consent'
    | '/diet'
    | '/emergency'
    | '/exercise'
    | '/faq'
    | '/home'
    | '/investigations'
    | '/kicks'
    | '/labor-signs'
    | '/login'
    | '/medical-disclaimer'
    | '/meds-safety'
    | '/more'
    | '/nutrition-guide'
    | '/onboarding'
    | '/postpartum'
    | '/privacy-policy'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/terms'
    | '/tracker'
    | '/vaccines-pregnancy'
    | '/welcome'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/consent'
    | '/diet'
    | '/emergency'
    | '/exercise'
    | '/faq'
    | '/home'
    | '/investigations'
    | '/kicks'
    | '/labor-signs'
    | '/login'
    | '/medical-disclaimer'
    | '/meds-safety'
    | '/more'
    | '/nutrition-guide'
    | '/onboarding'
    | '/postpartum'
    | '/privacy-policy'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/terms'
    | '/tracker'
    | '/vaccines-pregnancy'
    | '/welcome'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/baby'
    | '/community'
    | '/consent'
    | '/diet'
    | '/emergency'
    | '/exercise'
    | '/faq'
    | '/home'
    | '/investigations'
    | '/kicks'
    | '/labor-signs'
    | '/login'
    | '/medical-disclaimer'
    | '/meds-safety'
    | '/more'
    | '/nutrition-guide'
    | '/onboarding'
    | '/postpartum'
    | '/privacy-policy'
    | '/schemes'
    | '/signup'
    | '/symptoms'
    | '/terms'
    | '/tracker'
    | '/vaccines-pregnancy'
    | '/welcome'
    | '/yoga'
    | '/baby/care'
    | '/baby/feeds'
    | '/baby/growth'
    | '/baby/vaccinations'
    | '/community/$postId'
    | '/week/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BabyRoute: typeof BabyRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  DietRoute: typeof DietRoute
  EmergencyRoute: typeof EmergencyRoute
  ExerciseRoute: typeof ExerciseRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  InvestigationsRoute: typeof InvestigationsRoute
  KicksRoute: typeof KicksRoute
  LaborSignsRoute: typeof LaborSignsRoute
  LoginRoute: typeof LoginRoute
  MedicalDisclaimerRoute: typeof MedicalDisclaimerRoute
  MedsSafetyRoute: typeof MedsSafetyRoute
  MoreRoute: typeof MoreRoute
  NutritionGuideRoute: typeof NutritionGuideRoute
  OnboardingRoute: typeof OnboardingRoute
  PostpartumRoute: typeof PostpartumRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SchemesRoute: typeof SchemesRoute
  SignupRoute: typeof SignupRoute
  SymptomsRoute: typeof SymptomsRoute
  TermsRoute: typeof TermsRoute
  TrackerRoute: typeof TrackerRoute
  VaccinesPregnancyRoute: typeof VaccinesPregnancyRoute
  WelcomeRoute: typeof WelcomeRoute
  YogaRoute: typeof YogaRoute
  WeekWeekRoute: typeof WeekWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccines-pregnancy': {
      id: '/vaccines-pregnancy'
      path: '/vaccines-pregnancy'
      fullPath: '/vaccines-pregnancy'
      preLoaderRoute: typeof VaccinesPregnancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postpartum': {
      id: '/postpartum'
      path: '/postpartum'
      fullPath: '/postpartum'
      preLoaderRoute: typeof PostpartumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-guide': {
      id: '/nutrition-guide'
      path: '/nutrition-guide'
      fullPath: '/nutrition-guide'
      preLoaderRoute: typeof NutritionGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meds-safety': {
      id: '/meds-safety'
      path: '/meds-safety'
      fullPath: '/meds-safety'
      preLoaderRoute: typeof MedsSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-disclaimer': {
      id: '/medical-disclaimer'
      path: '/medical-disclaimer'
      fullPath: '/medical-disclaimer'
      preLoaderRoute: typeof MedicalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor-signs': {
      id: '/labor-signs'
      path: '/labor-signs'
      fullPath: '/labor-signs'
      preLoaderRoute: typeof LaborSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kicks': {
      id: '/kicks'
      path: '/kicks'
      fullPath: '/kicks'
      preLoaderRoute: typeof KicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$week': {
      id: '/week/$week'
      path: '/week/$week'
      fullPath: '/week/$week'
      preLoaderRoute: typeof WeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/baby/vaccinations': {
      id: '/baby/vaccinations'
      path: '/vaccinations'
      fullPath: '/baby/vaccinations'
      preLoaderRoute: typeof BabyVaccinationsRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/growth': {
      id: '/baby/growth'
      path: '/growth'
      fullPath: '/baby/growth'
      preLoaderRoute: typeof BabyGrowthRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/feeds': {
      id: '/baby/feeds'
      path: '/feeds'
      fullPath: '/baby/feeds'
      preLoaderRoute: typeof BabyFeedsRouteImport
      parentRoute: typeof BabyRoute
    }
    '/baby/care': {
      id: '/baby/care'
      path: '/care'
      fullPath: '/baby/care'
      preLoaderRoute: typeof BabyCareRouteImport
      parentRoute: typeof BabyRoute
    }
  }
}

interface BabyRouteChildren {
  BabyCareRoute: typeof BabyCareRoute
  BabyFeedsRoute: typeof BabyFeedsRoute
  BabyGrowthRoute: typeof BabyGrowthRoute
  BabyVaccinationsRoute: typeof BabyVaccinationsRoute
}

const BabyRouteChildren: BabyRouteChildren = {
  BabyCareRoute: BabyCareRoute,
  BabyFeedsRoute: BabyFeedsRoute,
  BabyGrowthRoute: BabyGrowthRoute,
  BabyVaccinationsRoute: BabyVaccinationsRoute,
}

const BabyRouteWithChildren = BabyRoute._addFileChildren(BabyRouteChildren)

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BabyRoute: BabyRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  ConsentRoute: ConsentRoute,
  DietRoute: DietRoute,
  EmergencyRoute: EmergencyRoute,
  ExerciseRoute: ExerciseRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  InvestigationsRoute: InvestigationsRoute,
  KicksRoute: KicksRoute,
  LaborSignsRoute: LaborSignsRoute,
  LoginRoute: LoginRoute,
  MedicalDisclaimerRoute: MedicalDisclaimerRoute,
  MedsSafetyRoute: MedsSafetyRoute,
  MoreRoute: MoreRoute,
  NutritionGuideRoute: NutritionGuideRoute,
  OnboardingRoute: OnboardingRoute,
  PostpartumRoute: PostpartumRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SchemesRoute: SchemesRoute,
  SignupRoute: SignupRoute,
  SymptomsRoute: SymptomsRoute,
  TermsRoute: TermsRoute,
  TrackerRoute: TrackerRoute,
  VaccinesPregnancyRoute: VaccinesPregnancyRoute,
  WelcomeRoute: WelcomeRoute,
  YogaRoute: YogaRoute,
  WeekWeekRoute: WeekWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
